#!/bin/sh

# script to compile arduino sketches and flash them w/o the IDE

ARDUINO_APP="/Applications/Arduino.app"
ESPRESSIF_DIR="$HOME/Documents/Arduino/hardware/espressif"

# defaults
PORT="/dev/cu.usbserial-A400h9rO"
SPEED=921600 
BOARD="esp8266" 
ABUILD=".abuild"


SKETCH="$1"
if [ "$SKETCH" = ""  ]; then
	echo "usage: abuild.sh sketch.ino [port [speed [board]]]"
	echo "   valid boards are: "
	echo "      heltec_wifi_lora_32"
	echo "      adafruit_feather_m0"
	echo "      esp8266"
	echo "   current port candidates are"
	ls /dev/cu.* | while read a; do
		if [ "$a" = "/dev/cu.Bluetooth-Incoming-Port" ]; then continue; fi
		if [ "$a" = "/dev/cu.SerialPort-1" ]; then continue; fi
		echo "      $a"
	done
	echo "   speed can be 115200, 230400, 460800, 921600"
	exit 1
fi

if [ ! -r "$SKETCH" ]; then
	echo "error: file $SKETCH not found"
	exit 1
fi

BNAME=$(basename $SKETCH)
WRKDIR=$(dirname $SKETCH)
if [ "$WRKDIR" = "." ]; then
	WRKDIR=$(pwd)
fi


BUILDDIR=$WRKDIR/build
if [ ! -d $BUILDDIR ]; then
	mkdir $BUILDDIR
fi

if [ ! -d "$ARDUINO_APP" ]; then
	echo "Ardhino IDE not found at $ARDUINO_APP"
	exit 1
fi
ARDUINOBUILDER=$ARDUINO_APP/Contents/Java/arduino-builder
if [ ! -x "$ARDUINOBUILDER" ]; then
	echo "arduino-builder not found in $ARDUINO_APP"
	exit 1
fi

if [ -r $ABUILD/.vars ]; then
	 . $ABUILD/.vars
fi

if [ "$2" != "" ]; then
	PORT="$2"
fi

if [ "$3" != "" ]; then
	SPEED="$3"
fi

if [ "$4" != "" ]; then
	BOARD="$4"
fi

if [ ! -r "$WRKDIR/$ABUILD/.json" ]; then
	if [ "$BOARD" = "esp8266" ]; then
		FQBN="esp8266:esp8266:huzzah:CpuFrequency=160,FlashSize=4M3M"	
		FLASH="esptool"
		CHIP="esp8266"
	elif  [ "$BOARD" = "adafruit_feather_m0" ]; then
		FQBN="adafruit:samd:adafruit_feather_m0"
		FLASH="bossac"
		CHIP="samd"
	elif  [ "$BOARD" = "heltec_wifi_lora_32" ]; then
		FQBN="espressif:esp32:heltec_wifi_lora_32:FlashFreq=80,UploadSpeed=230400"
		FLASH="esptool"
		CHIP="esp32"
	else
		echo "error: board $BOARD not supported"
		exit 2
	fi
	if [ "$FLASH" = "esptool" ]; then
		if  [ "$FLASHTOOL" = "" ]; then
			FLASHTOOL=$(which esptool.py)
			if [ ! -x "$FLASHTOOL" ]; then
				echo "error: esptool.py not found"
				exit 2
			fi
		fi
	elif [ "$FLASH" = "bossac" ]; then
		if [ "$FLASHTOOL" = "" ]; then
			FLASHTOOL=$(find $HOME/Library/Arduino15/packages  -name bossac -type f | xargs ls -rt | tail -1)
			if [ ! -x "$FLASHTOOL" ]; then
				echo "error: cannot find bossac"
				exit 2
			fi
		fi
	fi

	if [ ! -d "$WRKDIR/$ABUILD" ]; then
		mkdir "$WRKDIR/$ABUILD"
	fi

	echo "ARDUINO_APP=\"$ARDUINO_APP\"" >  $WRKDIR/$ABUILD/.vars
	echo "PORT=\"$PORT\"" >>  $WRKDIR/$ABUILD/.vars
	echo "SPEED=\"$SPEED\"" >>  $WRKDIR/$ABUILD/.vars
	echo "BOARD=\"$BOARD\"" >>  $WRKDIR/$ABUILD/.vars
	echo "SKETCH=\"$SKETCH\"" >>  $WRKDIR/$ABUILD/.vars
	echo "FLASH=\"$FLASH\"" >>  $WRKDIR/$ABUILD/.vars
	echo "CHIP=\"$CHIP\"" >>  $WRKDIR/$ABUILD/.vars
	echo "FLASHTOOL=\"$FLASHTOOL\"" >>  $WRKDIR/$ABUILD/.vars
	cat <<EOF >$WRKDIR/$ABUILD/.json   
{
  "builtInLibrariesFolders": "$ARDUINO_APP/Contents/Java/libraries",
  "customBuildProperties": "",
  "fqbn": "$FQBN",
  "hardwareFolders": "$ARDUINO_APP/Contents/Java/hardware,$HOME/Library/Arduino15/packages,$HOME/Documents/Arduino/hardware",
  "otherLibrariesFolders": "$ARDUINO_APP/Contents/Java/libraries,$HOME/Documents/Arduino/libraries",
  "runtime.ide.version": "10805",
  "toolsFolders": "$ARDUINO_APP/Contents/Java/tools-builder,$ARDUINO_APP/Contents/Java/hardware/tools/avr,$HOME/Library/Arduino15/packages,$HOME/Documents/Arduino/hardware"
}
EOF
fi


$ARDUINOBUILDER  -build-path $BUILDDIR -compile -build-options-file $WRKDIR/$ABUILD/.json  $SKETCH

if [ $? -ne 0 ]; then
	echo "compile failed"
	exit 1
fi
echo "flashing"

if [ "$FLASH" = "esptool" -a "$CHIP" = "esp8266" ]; then
  echo "put the ESP8266 in loader mode, hit <ENTER>"
  read a
  $FLASHTOOL --baud $SPEED --port $PORT --before default_reset --after hard_reset write_flash  0x00000 $BUILDDIR/"$BNAME.bin"
elif [ "$FLASH" = "bossac" ]; then
  echo "double-click the RST button on the Feather M0 board, hit <ENTER>"
  read a
  $FLASHTOOL --port=$PORT -U true -i -e -w -v $BUILDDIR/"$BNAME.bin" -R
elif [ "$FLASH" = "esptool" -a "$CHIP" = "esp32" ]; then
  echo "ready to flash? hit <ENTER>"
  read a

  $FLASHTOOL --baud $SPEED --port $PORT \
	--before default_reset \
	--after hard_reset write_flash \
	-z \
	--flash_mode dio \
	--flash_freq 80m \
	--flash_size detect \
 	 0xe000 $ESPRESSIF_DIR/esp32/tools/partitions/boot_app0.bin \
	 0x1000 $ESPRESSIF_DIR/esp32/tools/sdk/bin/bootloader_dio_80m.bin \
	0x10000 "$BUILDDIR/$BNAME.bin" \
	 0x8000 "$BUILDDIR/$BNAME.partitions.bin" 
fi
